/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-10-18 06:03:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submersionInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480903226000L));
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('.menu_main li').eq(2).addClass(\"on\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"get\">\r\n");
      out.write("\t<div id=\"container\" class=\"indInfo\">\r\n");
      out.write("\t<h3>Text 글자</h3>\r\n");
      out.write("        <ul class=\"tab\">\r\n");
      out.write("\t\t\t<li class=\"on\"><a href=\"#\">30mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">40mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">50mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">60mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">70mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">80mm</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">90mm</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"ltWd\">\r\n");
      out.write("\t\t\t<div class=\"cnt\"><img src=\"/images/samp_indInfo.png\" alt=\"\" /></div>\r\n");
      out.write("\t\t\t<ul class=\"legend\">\r\n");
      out.write("\t\t\t\t<li>안전</li>\r\n");
      out.write("\t\t\t\t<li>관심</li>\r\n");
      out.write("\t\t\t\t<li>주의</li>\r\n");
      out.write("\t\t\t\t<li>경계</li>\r\n");
      out.write("\t\t\t\t<li>심각</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"rtWd\">\r\n");
      out.write("\t\t\t<h3>예경보 정보 및 위험지구현황</h3>\r\n");
      out.write("\t\t\t<div class=\"tblwrap\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<col width=\"*\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"33%\" span=\"2\" />\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">구분</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">침수면적(ha)</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"col\">최대침수심(m)</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>침산지구</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>123</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>999</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tblwrap\">\r\n");
      out.write("\t\t\t\t<table class=\"fcstStus\">\r\n");
      out.write("\t\t\t\t\t<col width=\"*\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\" />\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>재해유형</td>\r\n");
      out.write("\t\t\t\t\t\t<td>내수재해</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\"><img width=\"140\" src=\"/images/samp_indInfo2.png\" alt=\"\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>3공단분구1지구</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>기호명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>IFP-W28</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위치</td>\r\n");
      out.write("\t\t\t\t\t\t<td>서구 비산동 2041-112번지 일원</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>조사일자</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2013. 09. 03</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>현장사진</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" src=\"/images/samp_indInfo3.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" src=\"/images/samp_indInfo4.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구특성</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">산업시설 및 밀집지역이며 금호강 수위대비 저지대 지역으로 3공단 빗물펌프장 유역에 해당됨</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위험요인</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>위험지구 주변 관거에 대한 정량적 분석(방재성능목표강우량 적용)을 검토한 결과 하류에 위치한 3공단빗물펌프장 용량 부족으로 우수흐름이 지체되어 침수발생이 되고 있는 것으로 검토됨.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>정량적 분석결과 하류인근에 위치한 3공단 빗물펌프장 용량부족으로 우수흐름이 지체되고 부분적으로 관거 통수단면이 부족하여 침수위험성이 있는 것으로 검토되어 빗물펌프장 증설 및 관거개선이 필요함.</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>예상피해</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상피해지역내 산업지역이 밀집해 있음.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>인구 및 자산조사 순위 : 75위(자산가치 67위, 인구순위 78위)</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해면적 : 6.88ha</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해액 : 1,073백만원</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>참고사항</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">내수재해위험지구 3공단빗물펌프장 저감대책으로 위험요인 해소</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
