/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-10-18 06:03:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class waterlevel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480903226000L));
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('.menu_main li').eq(3).addClass(\"on\");\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"get\">\r\n");
      out.write("\t<div id=\"container\" class=\"wtrLvl\">\r\n");
      out.write("    \t<div class=\"sett\">\r\n");
      out.write("\t\t\t<strong>현재시각</strong>\r\n");
      out.write("          \t<em>20019년 7월 01일 18시 00분</em>\r\n");
      out.write("          \t<span>|</span>\r\n");
      out.write("          \t<strong>날짜 선택</strong>\r\n");
      out.write("          \t<input name=\"\" value=\"2018.06.28\" class=\"\" type=\"text\" /><a href=\"#\"><img src=\"/images/calendar.png\" alt=\"\" /></a>\r\n");
      out.write("          \t<select name=\"\">\r\n");
      out.write("\t\t\t\t<option value=\"00\"><span style=\"font-size:18px;\">00</span></option>\r\n");
      out.write("            \t<option value=\"00\">01</option>\r\n");
      out.write("            \t<option value=\"00\">02</option>\r\n");
      out.write("          \t</select>\r\n");
      out.write("          \t<a href=\"#\"><img src=\"/images/btn_now.gif\" alt=\"Now\" /></a>\r\n");
      out.write("          \t\r\n");
      out.write("          \t<div class=\"sltWrap\">\r\n");
      out.write("\t            <select>\r\n");
      out.write("\t              <option value=\"\">지구</option>\r\n");
      out.write("\t            </select>\r\n");
      out.write("\t            <select name=\"\">\r\n");
      out.write("\t              <option value=\"\">지점?</option>\r\n");
      out.write("\t            </select>\r\n");
      out.write("          \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"ltWd\">\r\n");
      out.write("          \t<div class=\"crtwrap\">\r\n");
      out.write("            <div class=\"cnt\"><img src=\"/images/waterdepth.gif\" alt=\"\" /></div>\r\n");
      out.write("            <ul class=\"legend\">\r\n");
      out.write("              \t<li>안전</li>\r\n");
      out.write("              \t<li>관심</li>\r\n");
      out.write("              \t<li>주의</li>\r\n");
      out.write("              \t<li>경계</li>\r\n");
      out.write("              \t<li>심각</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tblwrap\">\r\n");
      out.write("      \t\t<table>\r\n");
      out.write("              \t<col width=\"*\" />\r\n");
      out.write("              \t<col width=\"25%\" span=\"2\" />\r\n");
      out.write("              \t<thead>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<th scope=\"col\">시간</th>\r\n");
      out.write("\t                  \t<th scope=\"col\">수위</th>\r\n");
      out.write("\t                  \t<th scope=\"col\">예경보</th>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("              \t</thead>\r\n");
      out.write("              \t<tbody>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>현시점</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                  \t<td>2019. 00.00 13:00</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                  \t<td>0.0</td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("              \t</tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"rtWd\">\r\n");
      out.write("          \t<h3>관측지점 및 계측기 정보</h3>\r\n");
      out.write("          \t<div class=\"\"><img width=\"330\" src=\"/images/samp_seoul.png\" alt=\"\" /></div>\r\n");
      out.write("          \t<ul>\r\n");
      out.write("            \t<li>- 초음파 방식</li>\r\n");
      out.write("            \t<li>- Max measure Range : 10m</li>\r\n");
      out.write("            \t<li>- Accuracy : ±0.5%</li>\r\n");
      out.write("            \t<li>- Operation power : DC 24V, / 300mA</li>\r\n");
      out.write("            \t<li>- Output Signal : 4~20mA，1~5V，RS485，RS232，1~10V </li>\r\n");
      out.write("            \t<li>- Operating Temperature: 0℃ to 50℃</li>\r\n");
      out.write("          \t</ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
