/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2021-08-11 09:34:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.main._03;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submersionInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1480903226000L));
    _jspx_dependants.put("jar:file:/C:/workspace/eclipse_workspace/hecorea/SMARTUF/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SMARTUF/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('.menu_main li').eq(2).addClass(\"on\");\r\n");
      out.write("\t$('.fcstStus').eq(0).show();\r\n");
      out.write("\t$('.fcstStus').eq(1).hide();\r\n");
      out.write("\tselectTable('01');\r\n");
      out.write("\t\r\n");
      out.write("\tvar container = document.getElementById('popup');\r\n");
      out.write("\tvar content = document.getElementById('popup-content');\r\n");
      out.write("\tvar overlay = new ol.Overlay(({element: container}));\r\n");
      out.write("\t\r\n");
      out.write("\tvar daegu_emd_layer = new ol.layer.Tile({\r\n");
      out.write("\t    source: new ol.source.TileWMS({\r\n");
      out.write("\t    \turl: 'http://geornd.hecorea.co.kr/smartuf/wms',\r\n");
      out.write("\t    \tparams: {\r\n");
      out.write("\t            'LAYERS': 'smartuf:daegu_emd'\r\n");
      out.write("\t        },\r\n");
      out.write("\t        opaque: false,\r\n");
      out.write("\t        serverType: 'geoserver',\r\n");
      out.write("\t        crossOrigin : 'anonymous'\r\n");
      out.write("\t    })\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar daegu_gugun_layer = new ol.layer.Tile({\r\n");
      out.write("\t    source: new ol.source.TileWMS({\r\n");
      out.write("\t    \turl: 'http://geornd.hecorea.co.kr/smartuf/wms',\r\n");
      out.write("\t    \tparams: {\r\n");
      out.write("\t            'LAYERS': 'smartuf:daegu_gugun'\r\n");
      out.write("\t        },\r\n");
      out.write("\t        opaque: false,\r\n");
      out.write("\t        serverType: 'geoserver',\r\n");
      out.write("\t        crossOrigin : 'anonymous'\r\n");
      out.write("\t    })\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar daegu_si_layer = new ol.layer.Tile({\r\n");
      out.write("\t    source: new ol.source.TileWMS({\r\n");
      out.write("\t    \turl: 'http://geornd.hecorea.co.kr/smartuf/wms',\r\n");
      out.write("\t    \tparams: {\r\n");
      out.write("\t            'LAYERS': 'smartuf:daegu_si'\r\n");
      out.write("\t        },\r\n");
      out.write("\t        opaque: false,\r\n");
      out.write("\t        serverType: 'geoserver',\r\n");
      out.write("\t        crossOrigin : 'anonymous'\r\n");
      out.write("\t    })\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar daegu_point = new ol.layer.Tile({\r\n");
      out.write("\t    source: new ol.source.TileWMS({\r\n");
      out.write("\t    \turl: 'http://geornd.hecorea.co.kr/smartuf/wms',\r\n");
      out.write("\t    \tparams: {\r\n");
      out.write("\t            'LAYERS': 'smartuf:daegu_point'\r\n");
      out.write("\t        },\r\n");
      out.write("\t        opaque: false,\r\n");
      out.write("\t        serverType: 'geoserver',\r\n");
      out.write("\t        crossOrigin : 'anonymous'\r\n");
      out.write("\t    })\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tmap = new ol.Map({\r\n");
      out.write("\t    logo: false,\r\n");
      out.write("\t    target: 'map',\r\n");
      out.write("\t    overlays: [overlay],\r\n");
      out.write("\t    //layers: [new ol.layer.Tile({source: new ol.source.OSM()}), layer_all_basin],\r\n");
      out.write("\t    layers: [new ol.layer.Tile({source: new ol.source.OSM()}), daegu_danger_layer, daegu_danger_sc_layer, daegu_danger_bc_layer, daegu_danger_rp_layer, daegu_danger_sk_layer, daegu_emd_layer, daegu_gugun_layer, daegu_si_layer, daegu_point],\r\n");
      out.write("\t    view: new ol.View({\r\n");
      out.write("\t        projection : global_projection,\r\n");
      out.write("\t        //center: [128.5724234, 35.891653], //126.62, 36.33 35.891653,128.5724234\r\n");
      out.write("\t        center: [128.632566, 35.882781], //126.62, 36.33 35.891653,128.5724234\r\n");
      out.write("\t        zoom: 13.4 //9.2\r\n");
      out.write("\t        //minZoom: 8.0\r\n");
      out.write("\t    })\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function selectData() {\r\n");
      out.write("\tvar node_cd = $('#node_cd').val();\r\n");
      out.write("\t\r\n");
      out.write("\tdaegu_danger_layer.getSource().updateParams({LAYERS : \"smartuf:flood_new_output_2dis_0\" + node_cd + \"mm_060m_3q\"});\r\n");
      out.write("\tdaegu_danger_sc_layer.getSource().updateParams({LAYERS : \"smartuf:flood_sc_output_2dis_0\" + node_cd + \"mm\"});\r\n");
      out.write("\tdaegu_danger_bc_layer.getSource().updateParams({LAYERS : \"smartuf:flood_bc_output_2dis_0\" + node_cd + \"mm\"});\r\n");
      out.write("\tdaegu_danger_rp_layer.getSource().updateParams({LAYERS : \"smartuf:flood_rp_output_2dis_0\" + node_cd + \"mm\"});\r\n");
      out.write("\tdaegu_danger_sk_layer.getSource().updateParams({LAYERS : \"smartuf:flood_sk_output_2dis_0\" + node_cd + \"mm\"});\r\n");
      out.write("\t//\"smartuf:flood_sc_output_2dis_0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectTable(param) {\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: \"POST\",\r\n");
      out.write("\t\turl: \"/floodCont/selectSubmersionData.do\",\r\n");
      out.write("\t\tdataType: \"json\",\r\n");
      out.write("\t\tasync : false,\r\n");
      out.write("\t\tdata: {'infoId': param},\r\n");
      out.write("\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\tconsole.log(data.dataList.length);\r\n");
      out.write("\t\t\t$('#text_name').html(\"<h4>\" + data.dataList[0].infoName + \"</h4>\");\r\n");
      out.write("\t\t\t$('#text_dist_type').html(data.dataList[0].distType);\r\n");
      out.write("\t\t\t$('#text_info_name').html(data.dataList[0].infoName);\r\n");
      out.write("\t\t\t$('#text_info_model').html(data.dataList[0].infoModel);\r\n");
      out.write("\t\t\t$('#text_loc').html(data.dataList[0].loc);\r\n");
      out.write("\t\t\t$('#text_info_dt').html(data.dataList[0].infoDt);\r\n");
      out.write("\t\t\t$('#ul_quality').html(data.dataList[0].quality);\r\n");
      out.write("\t\t\t$('#ul_reason').html(data.dataList[0].reason);\r\n");
      out.write("\t\t\t$('#ul_forecast').html(data.dataList[0].forecast);\r\n");
      out.write("\t\t\t$('#text_etc').html(data.dataList[0].etc);\r\n");
      out.write("\t\t\t$('#img_dist_type').attr(\"src\", \"/images/submersion/\" + data.dataList[0].infoId + \"_00.jpg\");\r\n");
      out.write("\t\t\t$('#img_field_01').attr(\"src\", \"/images/submersion/\" + data.dataList[0].infoId + \"_01.jpg\");\r\n");
      out.write("\t\t\t$('#img_field_02').attr(\"src\", \"/images/submersion/\" + data.dataList[0].infoId + \"_02.jpg\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '.tab li', function() {\r\n");
      out.write("\tvar current_class = $(this).attr('class');\r\n");
      out.write("\t\r\n");
      out.write("\tif(!$(this).hasClass(\"on\")) {\r\n");
      out.write("\t\t$('.tab li').removeClass(\"on\");\r\n");
      out.write("\t\t$('.' + current_class).addClass(\"on\");\r\n");
      out.write("\t\t$('#node_cd').val(current_class);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tselectData();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).on('change', '#select_area', function() {\r\n");
      out.write("\tvar select_area = $('#select_area option:selected').val();\r\n");
      out.write("\tselectTable(select_area);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/*\r\n");
      out.write("\tif(select_area == 'option_a') {\r\n");
      out.write("\t\t$('.fcstStus').eq(0).show();\r\n");
      out.write("\t\t$('.fcstStus').eq(1).hide();\r\n");
      out.write("\t\t$('#text_name').html(\"<h4>3공단분구1지구</h4>\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\t$('.fcstStus').eq(0).hide();\r\n");
      out.write("\t\t$('.fcstStus').eq(1).show();\r\n");
      out.write("\t\t$('#text_name').html(\"<h4>침산분구1지구</h4>\");\r\n");
      out.write("\t}\r\n");
      out.write("\t*/\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"get\">\r\n");
      out.write("<input type=\"hidden\" id=\"node_cd\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nodeCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' />\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container\" class=\"indInfo\">\r\n");
      out.write("        <ul class=\"tab\">\r\n");
      out.write("\t\t\t<li class=\"30 on\"><a href=\"#\">30mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"40\"><a href=\"#\">40mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"50\"><a href=\"#\">50mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"60\"><a href=\"#\">60mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"70\"><a href=\"#\">70mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"80\"><a href=\"#\">80mm</a></li>\r\n");
      out.write("\t\t\t<li class=\"90\"><a href=\"#\">90mm</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"ltWd\">\r\n");
      out.write("\t\t\t<div class=\"cnt\" id=\"map\"><!-- <img src=\"//images/samp_indInfo.png\" alt=\"\" /> --></div>\r\n");
      out.write("\t\t\t<ul class=\"legend\">\r\n");
      out.write("\t\t\t\t<li>안전</li>\r\n");
      out.write("\t\t\t\t<li>관심</li>\r\n");
      out.write("\t\t\t\t<li>주의</li>\r\n");
      out.write("\t\t\t\t<li>경계</li>\r\n");
      out.write("\t\t\t\t<li>심각</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"rtWd\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h3>홍수 위험지구 현황</h3>\r\n");
      out.write("            <div class=\"nameSelt\">\r\n");
      out.write("                <div id=\"text_name\"><h4>3공단분구1지구</h4></div>\r\n");
      out.write("                <select id=\"select_area\">\r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \t<!--  \r\n");
      out.write("                    <option value=\"option_a\">3공단분구1지구</option>\r\n");
      out.write("                    <option value=\"option_b\">침산분구1지구</option>\r\n");
      out.write("                    -->\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t<div class=\"tblwrap\">\r\n");
      out.write("\t\t\t\t<!--  \r\n");
      out.write("\t\t\t\t<table class=\"fcstStus\">\r\n");
      out.write("\t\t\t\t\t<col width=\"*\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\" />\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>재해유형</td>\r\n");
      out.write("\t\t\t\t\t\t<td>내수재해</td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\"><img width=\"140\" src=\"/images/samp_indInfo2.png\" alt=\"\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>3공단분구1지구</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>기호명</td>\r\n");
      out.write("\t\t\t\t\t\t<td>IFP-W28</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위치</td>\r\n");
      out.write("\t\t\t\t\t\t<td>서구 비산동 2041-112번지 일원</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>조사일자</td>\r\n");
      out.write("\t\t\t\t\t\t<td>2013. 09. 03</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>현장사진</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" src=\"/images/samp_indInfo3.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" src=\"/images/samp_indInfo4.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구특성</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">산업시설 및 밀집지역이며 금호강 수위대비 저지대 지역으로 3공단 빗물펌프장 유역에 해당됨</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위험요인</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>위험지구 주변 관거에 대한 정량적 분석(방재성능목표강우량 적용)을 검토한 결과 하류에 위치한 3공단빗물펌프장 용량 부족으로 우수흐름이 지체되어 침수발생이 되고 있는 것으로 검토됨.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>정량적 분석결과 하류인근에 위치한 3공단 빗물펌프장 용량부족으로 우수흐름이 지체되고 부분적으로 관거 통수단면이 부족하여 침수위험성이 있는 것으로 검토되어 빗물펌프장 증설 및 관거개선이 필요함.</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>예상피해</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상피해지역내 산업지역이 밀집해 있음.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>인구 및 자산조사 순위 : 75위(자산가치 67위, 인구순위 78위)</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해면적 : 6.88ha</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해액 : 1,073백만원</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>참고사항</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">내수재해위험지구 3공단빗물펌프장 저감대책으로 위험요인 해소</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!-- 침산분구1지구 -->\r\n");
      out.write("\t\t\t\t<table class=\"fcstStus\">\r\n");
      out.write("\t\t\t\t\t<col width=\"*\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"30%\" />\r\n");
      out.write("\t\t\t\t\t<col width=\"50%\" />\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>재해유형</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"text_dist_type\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td rowspan=\"5\"><img id=\"img_dist_type\" width=\"140\" src=\"/images/samp_indInfo5.png\" alt=\"\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구명</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"text_info_name\">침산분구1지구</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>기호명</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"text_info_model\">IFP-N16</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위치</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"text_loc\">북구 침산동 772번지 일원</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>조사일자</td>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"text_info_dt\">2013. 09. 05</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>현장사진</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" id=\"img_field_01\" src=\"/images/samp_indInfo6.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img width=\"119\" id=\"img_field_02\" src=\"/images/samp_indInfo7.png\" alt=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>지구특성</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("                            <ul id=\"ul_quality\">\r\n");
      out.write("                                <!--<li>금호강 우안( No.36+400) 제내지 지역에 신천대로와 접속도로 부근이며, 주변 지역은 대부분 공장지대로 형성되어 있음</li>\r\n");
      out.write("                                <li>하수관로의 구배가 완만하여 배수의 흐름이 원활하지 못함.</li>\r\n");
      out.write("                                <li>저지대로 인한 금호강의 홍수위 상승시 배수지체가 발생하여 도로침수</li>-->\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>위험요인</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"ul_reason\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--<li>위험지구 주변 관거에 대한 정량적 분석(방재성능목표강우량 적용)을 검토한 결과 하구에 위치한 침산 빗물펌프</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>하구에 위치한 침산 빗물펌프장 용량부족으로 인해 관로내 우수가 원활하게 배수되지 않아 침수(최대침수심 1.14m)가 발생되고 있어 침산빗물펌프장 용량 증설 필요</li>-->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>예상피해</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"ul_forecast\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--<li>예상피해지역내 주거지역과 상업지역이 입지함.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>인구 및 자산조사 순위 : 80위(자산가치 76위, 인구순위 82위)</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해면적 : 3.0ha</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>예상 피해액 : 609백만원</li>-->\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>참고사항</td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" id=\"text_etc\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <!-- /2019-10-23 수정 end -->\r\n");
      out.write("            \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/include/common_footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/main/03/submersionInfo.jsp(182,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("dl");
    // /WEB-INF/jsp/main/03/submersionInfo.jsp(182,17) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/main/03/submersionInfo.jsp(182,17) '${dataList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dataList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("              \t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dl.infoId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dl.infoName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
